### ISSUE TITLE
gpt2 example is not executable

### ISSUE THREAD

**Issue by gpengzhi** [asyml/forte#41]
Run

```
python multipack_pipeline_gpt2.py
```

Have

```
Traceback (most recent call last):
  File "multipack_pipeline_gpt2.py", line 8, in <module>
    pl.init_from_config_path("sample_multipack_pipeline_gpt.yml")
  File "/Users/pengzhi.gao/Desktop/my_git/forte/forte/base_pipeline.py", line 121, in init_from_config_path
    self.init_from_config(configs)
  File "/Users/pengzhi.gao/Desktop/my_git/forte/forte/multipack_pipeline.py", line 47, in init_from_config
    class_args=reader_config.get("kwargs", {}),
  File "/Users/pengzhi.gao/Desktop/my_git/forte/forte/multipack_pipeline.py", line 85, in create_class_with_kwargs
    cls = get_class(class_name)
  File "/Users/pengzhi.gao/Desktop/my_git/forte/forte/utils.py", line 70, in get_class
    "Class not found in {}: {}".format(module_paths, class_name))
ValueError: Class not found in None: PlainSentenceTxtgenReader
```

**Comment by AvinashBukkittu** [comment]
GPT2 example is updated as part of https://github.com/asyml/forte/pull/60/. `PlainSentenceTxtgenReader` is renamed to `MultiPackSentenceReader`
