### ISSUE TITLE
process_string_example.py is not executable

### ISSUE THREAD

**Issue by gpengzhi** [asyml/forte#43]
Run

```
python process_string_example.py
```

Have

```
Traceback (most recent call last):
  File "process_string_example.py", line 152, in <module>
    main()
  File "process_string_example.py", line 128, in main
    1:3]
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by AvinashBukkittu** [comment]
This should be fixed as part of https://github.com/asyml/forte/pull/60/
