### ISSUE TITLE
example chat bot configuration error. #700

### ISSUE THREAD

**Issue by bhaskar2443053** [asyml/forte#700]
**Describe the bug**
following the read.me in chartbot example. encounters configuration error.

**To Reproduce**
1. Prepare data `...`
2. Run command '....'
python download_models.py --model-name chatbot-bert
python download_models.py --model-name indexer
python download_models.py --model-name srl
python chatbot_example.py
error appears on 4th command:
 
(forte) bhaskarrao@LM00824BRAO chatbot % python chatbot_example.py
Traceback (most recent call last):
  File "/Users/bhaskarrao/opt/anaconda3/envs/forte/lib/python3.9/site-packages/forte/common/configurable.py", line 105, inmake_configs
    final_configs = Config(
  File "/Users/bhaskarrao/opt/anaconda3/envs/forte/lib/python3.9/site-packages/texar/torch/hyperparams.py", line 160, in __init__
    parsed_hparams = self._parse(
  File "/Users/bhaskarrao/opt/anaconda3/envs/forte/lib/python3.9/site-packages/texar/torch/hyperparams.py", line 226, in _parse
    raise ValueError(
ValueError: Unknown hyperparameter: query_pack_name. Only hyperparameters named 'kwargs' hyperparameters can contain new entries undefined in default hyperparameters.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/bhaskarrao/Documents/forte/examples/chatbot/chatbot_example.py", line 128, in <module>
    main(all_config)
  File "/Users/bhaskarrao/Documents/forte/examples/chatbot/chatbot_example.py", line 75, in main
    query_pipeline = setup(config)
  File "/Users/bhaskarrao/Documents/forte/examples/chatbot/chatbot_example.py", line 44, in setup
    query_pipeline.add(component=SearchProcessor(), config=config.searcher)
  File "/Users/bhaskarrao/opt/anaconda3/envs/forte/lib/python3.9/site-packages/forte/pipeline.py", line 829, in add
    self.component_configs.append(component.make_configs(config))
  File "/Users/bhaskarrao/opt/anaconda3/envs/forte/lib/python3.9/site-packages/forte/common/configurable.py", line 109, inmake_configs
    raise ProcessorConfigError(
forte.common.exception.ProcessorConfigError: Configuration error for the processor forte.processors.ir.search_processor.SearchProcessor.

**Expected behavior**

**Screenshots**
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/17160282/160070882-bfcbf6b5-7955-4e5e-85b7-dce076b65d5d.png">

**Environment (please complete the following information):**
 - OS: [e.g. iOS]. Mac
 - Python and Package verions: [e.g. Python version, Pytorch version]

**Additional context**

**Comment by feipenghe** [comment]
Can you try remove `query_pack_name` in the configuration file `config.yml`? I think API might changed since I added the line last time.

**Comment by bhaskar2443053** [comment]
after removing query_pack_name. new error shows up.

(forte) bhaskarrao@LM00824BRAO chatbot % python chatbot_example.py
Traceback (most recent call last):
  File "/Users/bhaskarrao/Documents/forte/examples/chatbot/chatbot_example.py", line 128, in <module>
    main(all_config)
  File "/Users/bhaskarrao/Documents/forte/examples/chatbot/chatbot_example.py", line 75, in main
    query_pipeline = setup(config)
  File "/Users/bhaskarrao/Documents/forte/examples/chatbot/chatbot_example.py", line 36, in setup
    reader=MultiPackTerminalReader(), config=config.reader
  File "/Users/bhaskarrao/opt/anaconda3/envs/forte/lib/python3.9/site-packages/texar/torch/hyperparams.py", line 301, in __getattr__
    raise AttributeError("Unknown hyperparameter: %s" % name)
AttributeError: Unknown hyperparameter: reader


any solution for this ?

**Comment by munachisonwadike** [comment]
Hello! 👋🏿  👋🏿 @feipenghe 
I am having the exact same error as well, vertabim actually
Actually I noticed that `query_pack_name` is present in the config.yml for `query_creator`, `indexer`, and even `searcher`.
Would you recommend it be removed for all three sections?
Thank you so much
Warm regards,

**Screenshot 1**
![image](https://user-images.githubusercontent.com/22077758/160431021-a243d1d6-8df8-4006-af0b-760cf5981f9b.png)

**Screenshot 2**

![image](https://user-images.githubusercontent.com/22077758/160431267-0b4acb5f-8048-4fa2-a05c-45ee989d6ef1.png)
