### ISSUE TITLE
Numpy version issue with fortex

### ISSUE THREAD

**Issue by feipenghe** [asyml/forte#709]
**Describe the bug**
Following up reproducing https://github.com/asyml/forte/issues/700 ,
I fixed some outdated configurations and found numpy version issue.

I installed `numpy==1.19.5` by installing `fortex/src/faiss` and running `chatbot_example.py` 
```
/home/murphy/Petuum/forte/forte/data/selector.py:138: UserWarning: Passing parameters through __init__ is deprecated, and does not work well with pipeline serialization.
  "Passing parameters through __init__ is deprecated,"
WARNING:root:Re-declared a new class named [ConstituentNode], which is probably used in import.
Using cached pre-trained BERT checkpoint from /home/murphy/texar_data/BERT/bert-base-uncased.
Using cached pre-trained BERT checkpoint from /home/murphy/texar_data/BERT/bert-base-uncased.
2022-03-29 21:21:12.530473: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-29 21:21:12.530505: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Loading TensorFlow models in PyTorch requires installing TensorFlow. Please see https://www.tensorflow.org/install/ for installation instructions.
Traceback (most recent call last):
  File "chatbot_example.py", line 129, in <module>
    main(all_config)
  File "chatbot_example.py", line 76, in main
    query_pipeline = setup(config)
  File "chatbot_example.py", line 70, in setup
    query_pipeline.initialize()
  File "/home/murphy/Petuum/forte/forte/pipeline.py", line 680, in initialize
    self.initialize_components()
  File "/home/murphy/Petuum/forte/forte/pipeline.py", line 724, in initialize_components
    component.initialize(self.resource, config)
  File "/home/murphy/Petuum/forte/forte/processors/ir/bert_based_query_creator.py", line 55, in initialize
    pretrained_model_name=self.config.model.name
  File "/home/murphy/anaconda3/envs/forte_org_env/lib/python3.7/site-packages/texar/torch/modules/encoders/bert_encoder.py", line 99, in __init__
    self.init_pretrained_weights()
  File "/home/murphy/anaconda3/envs/forte_org_env/lib/python3.7/site-packages/texar/torch/modules/pretrained/pretrained_base.py", line 148, in init_pretrained_weights
    self.pretrained_model_dir, *args, **kwargs)
  File "/home/murphy/anaconda3/envs/forte_org_env/lib/python3.7/site-packages/texar/torch/modules/pretrained/bert.py", line 354, in _init_from_checkpoint
    import tensorflow as tf
  File "/home/murphy/anaconda3/envs/forte_org_env/lib/python3.7/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/murphy/anaconda3/envs/forte_org_env/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/home/murphy/anaconda3/envs/forte_org_env/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 35, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "/home/murphy/anaconda3/envs/forte_org_env/lib/python3.7/site-packages/tensorflow/python/client/pywrap_tf_session.py", line 19, in <module>
    from tensorflow.python.client._pywrap_tf_session import *
ImportError: SystemError: <built-in method __contains__ of dict object at 0x7fbd33152370> returned a result with an error set
```
In conclude, it's tensorflow not installed correctly. As there is error reported while installing `numpy`
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.8.0 requires numpy>=1.20, but you have numpy 1.19.5 which is incompatible.
```

Then I tried upgrade `numpy==1.21` and running `chatbot_example.py`. It gives error

```
/home/murphy/Petuum/forte/forte/data/selector.py:138: UserWarning: Passing parameters through __init__ is deprecated, and does not work well with pipeline serialization.
  "Passing parameters through __init__ is deprecated,"
WARNING:root:Re-declared a new class named [ConstituentNode], which is probably used in import.
Using cached pre-trained BERT checkpoint from /home/murphy/texar_data/BERT/bert-base-uncased.
Using cached pre-trained BERT checkpoint from /home/murphy/texar_data/BERT/bert-base-uncased.
2022-03-29 21:13:48.034894: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-29 21:13:48.034925: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "chatbot_example.py", line 129, in <module>
    main(all_config)
  File "chatbot_example.py", line 76, in main
    query_pipeline = setup(config)
  File "chatbot_example.py", line 70, in setup
    query_pipeline.initialize()
  File "/home/murphy/Petuum/forte/forte/pipeline.py", line 680, in initialize
    self.initialize_components()
  File "/home/murphy/Petuum/forte/forte/pipeline.py", line 724, in initialize_components
    component.initialize(self.resource, config)
  File "/home/murphy/Petuum/forte/forte/processors/ir/search_processor.py", line 37, in initialize
    class_args={"config": self.configs.indexer_configs},
  File "/home/murphy/Petuum/forte/forte/utils/utils.py", line 145, in create_class_with_kwargs
    obj = cls(**class_args)
  File "/home/murphy/anaconda3/envs/forte_org_env/lib/python3.7/site-packages/fortex/faiss/embedding_based_indexer.py", line 67, in __init__
    index_class = utils.get_class(index_type, module_paths=["faiss"])
  File "/home/murphy/Petuum/forte/forte/utils/utils.py", line 106, in get_class
    "Class not found in {}: {}".format(module_paths, class_name)
ValueError: Class not found in ['faiss']: GpuIndexFlatIP
```

I think it's because `pytorch` is not installed correctly. As it gives dependency errors while I installed the package.

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
texar-pytorch 0.1.3 requires numpy<=1.19.5,>=1.16.6, but you have numpy 1.21.5 which is incompatible.
stanza 1.0.1 requires torch>=1.3.0, but you have torch 1.1.0 which is incompatible.
forte-huggingface 0.0.2 requires numpy==1.19.5, but you have numpy 1.21.5 which is incompatible.
forte-huggingface 0.0.2 requires transformers==4.2.2, but you have transformers 4.11.3 which is incompatible.
forte-allennlp 0.0.2 requires torch>=1.5.0, but you have torch 1.1.0 which is incompatible.
allennlp 1.2.0 requires torch<1.8.0,>=1.6.0, but you have torch 1.1.0 which is incompatible.
allennlp 1.2.0 requires transformers<3.5,>=3.1, but you have transformers 4.11.3 which is incompatible.
```

**To Reproduce**
1. Prepare data `...`
2. Run command '....'
3. See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Python and Package verions: [e.g. Python version, Pytorch version]

**Additional context**

**Comment by feipenghe** [comment]
it's actually unrelated to these packages. It's simply because `faiss` is not installed.
