### ISSUE TITLE
Improve the `clinical_pipeline` example

### ISSUE THREAD

**Issue by mylibrar** [asyml/forte#745]
**Is your feature request related to a problem? Please describe.**
The current [clinical_pipeline](https://github.com/asyml/forte/tree/master/examples/clinical_pipeline) example needs to be fixed according to the latest [updates](https://github.com/asyml/stave/commit/c09ab5d987109dd1c45459da08a2582fcea85877#diff-d9fe757a2162ba6785dd721f7fff50d7cba0d4ae769cd34782406fe6ec59922b) in `stave` of how to handle remote pipeline service. `stave` will no longer assemble an NLP pipeline itself. Instead, `stave` now uses a [pipeline](https://github.com/asyml/stave/blob/master/simple-backend/stave_backend/handlers/nlp.py#L49) with `RemoteProcessor` to call remote service. 

**Describe the solution you'd like**
Some of the steps in [README.md](https://github.com/asyml/forte/blob/master/examples/clinical_pipeline/README.md) might not work anymore. Hence we need to improve the example to make it solid:
* [Install extra dependencies](https://github.com/asyml/forte/blob/master/examples/clinical_pipeline/README.md#install-extra-dependencies): The command line to install forte-wrappers[elastic,nltk] might no longer work and we need to update it based on [forte-wrapper repo](https://github.com/asyml/forte-wrappers).
* [Prepare elastic searcher](https://github.com/asyml/forte/blob/master/examples/clinical_pipeline/README.md#prepare-elastic-searcher): We may want to point out a specific version for user to download and install since the latest elasticsearch(8.1.2) is not compatible with this example.
* [Run Indexer](https://github.com/asyml/forte/blob/master/examples/clinical_pipeline/README.md#run-indexer): Here we should provide a download link to `mimiciii/1.4/NOTEEVENTS.csv.gz`. For example, https://physionet.org/content/mimiciii-demo/1.4/D_ICD_DIAGNOSES.csv.
* [Stave](https://github.com/asyml/forte/blob/master/examples/clinical_pipeline/README.md#stave):
  * We want to provide a remote pipeline service for `LastUtteranceSearcher`. It should be similar to this [tutorial](https://asyml-forte.readthedocs.io/en/latest/notebook_tutorial/tutorial_eliza.html#Create-Your-Own-Chatbot-Service). The instruction will no longer require users to define the environment variables since they should be already configured in the service pipeline, but we still need to include the steps of starting a remote service.
  * [utterance_searcher.py](https://github.com/asyml/forte/blob/master/examples/clinical_pipeline/utterance_searcher.py) needs to be refactored. Currently it's directly modifying the `stave` database, and this is not a safe operation. We should utilize backend APIs to interact with `stave` database. A [wrapper](https://github.com/asyml/stave/blob/master/simple-backend/stave_backend/lib/stave_session.py) of these APIs is provided in `stave` backend lib.
  * The example requires user to setup two `stave` projects and to manually configure the database path. With the new [interfaces](https://github.com/mylibrar/stave/blob/master/simple-backend/stave_backend/lib/) provided by `stave`, we can automate these steps in a python script. Ideally users only need to run a python script, which should pop out a chatbot window for users to enter queries.

**Comment by Piyush13y** [comment]
This is not with regards to remote processing of stave, but I was just testing out stave with some json annotated output. I uploaded the base annotations first (which isn't base_ontology.json but a customized ontology json, where in I just had `DrugLookupWindowAnnotation`, `NegationContext`, `UMLSConceptLink`, `MedicalEntityMention` and `MedicalArticle`. However, when I upload the data pack json output in the next page, I see only `DrugLookupWindowAnnotation` and `NegationContext` in the left pane (output does have `MedicalEntityMention` annotations). I am not sure why that's happening.

**Comment by hunterhector** [comment]
There are two places that could affect this, we know that this is not very smooth right now:
1. https://github.com/asyml/forte/blob/master/forte/pipeline.py#L197, currently our pipeline will use `base_ontology` to populate an internal ontology if not provided. So most likely it didn't take all the new entry types you defined.
2. The project config to Stave will further determine which types will be shown on the left pane https://github.com/asyml/forte/blob/master/forte/processors/stave/stave_processor.py#L281 

As for 1, right now we are working on some new mechanism to populate the ontology, in the future, we should have all "used" entry types, but not just `base_ontology`. But this is not yet implemented.

As for 2, @mylibrar may know some details. I forget how we define the default configs.

**Comment by hunterhector** [comment]
Quick fix for 1 is to feed an ontology file to Pipeline at the begining. Note that it need to be a "full" ontology file, this can be obtained by using the "merged" option here: https://asyml-forte.readthedocs.io/en/latest/toc/ontology_generation.html#ontology-generation-steps

**Comment by Piyush13y** [comment]
Thanks @hunterhector. 
To clarify, I am currently just using an ontology json file and the output json file to work with a new Stave project. When I check the output json file, I do see new entry type annotations being detected which means pipeline did work with expected ontologies; however, when I upload the output data packs, I don't see the new types in the left pane. So its most likely the 2nd point that you mentioned that could be the culprit?

**Comment by mylibrar** [comment]
Thanks for the feedback. Could you provide the ontology.json and datapack.json that you used for testing? I'll try to replicate this issue on my side.

**Comment by hunterhector** [comment]
>>> I do see new entry type annotations being detected which means the pipeline did work with expected ontologies;
So the output json will definitely work, but that doesn't mean the types are passed to stave, you need to check this variable imparticular: https://github.com/asyml/forte/blob/master/forte/processors/stave/stave_processor.py#L152

Actually, I am pretty sure that if you didn't pass your ontology through `Pipeline` initialization, Stave won't be able to pick i t up.

**Comment by Piyush13y** [comment]
> Thanks for the feedback. Could you provide the ontology.json and datapack.json that you used for testing? I'll try to replicate this issue on my side.

Onto_temp is the ontology json file, the other file is the output datapack
[onto_temp.json.zip](https://github.com/asyml/forte/files/8544815/onto_temp.json.zip)
[211230762558809616268911394647227693964.json.zip](https://github.com/asyml/forte/files/8544820/211230762558809616268911394647227693964.json.zip)

**Comment by mylibrar** [comment]
I think the reason why you can only see `DrugLookupWindowAnnotation` and `NegationContext` in the left pane is that `stave` is [skipping](https://github.com/asyml/stave/blob/4be7ccdead51324100dc4befbeb5aefa6565daf2/src/app/pages/Projects.tsx#L140) all the `Generics` entries when generating the legends. Actually this is an expected behavior because it's hard for `stave` to render the `Generics` type. So if you want `stave` to display all the ontology definitions, maybe you can reconsider the ontology designing and use more `Annotation`s and `Link`s.

**Comment by Piyush13y** [comment]
@mylibrar On a completely different note, I was able to start stave server without any problem until today. I then reinstalled it from source and now it throws 500s. I am sure its some small thing that I am missing but I tried some stuff out and wasnt able to resolve it. Please advise. Following is the stack trace for the issue:

```
(base) piyush@Piyushs-Air simple-backend % stave start -o -n 8880
For more details, check out log file at /Users/piyush/.stave/log.
Starting Stave server at http://localhost:8880.
Quit the server with CONTROL-C.

[ERROR] 2022-04-26 17:58:32,394 web Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:8880', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/piyush/miniforge3/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/piyush/casl/stave/simple-backend/stave_backend/lib/stave_viewer.py", line 214, in get
    self.render(self._build_path + "/index.html")
  File "/Users/piyush/miniforge3/lib/python3.9/site-packages/tornado/web.py", line 863, in render
    html = self.render_string(template_name, **kwargs)
  File "/Users/piyush/miniforge3/lib/python3.9/site-packages/tornado/web.py", line 1009, in render_string
    t = loader.load(template_name)
  File "/Users/piyush/miniforge3/lib/python3.9/site-packages/tornado/template.py", line 446, in load
    self.templates[name] = self._create_template(name)
  File "/Users/piyush/miniforge3/lib/python3.9/site-packages/tornado/template.py", line 477, in _create_template
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/piyush/casl/stave/simple-backend/stave_backend/lib/build/index.html'
[ERROR] 2022-04-26 17:58:32,398 web 500 GET / (::1) 4.77ms
```

**Comment by mylibrar** [comment]
The recommended method to install `stave` is `pip install stave==0.0.2.dev1`. Right now installing `stave` directly from source might not work because there's actually some extra steps to build the package:
* `cd` into `stave/`
* You need to run `yarn build` to generate a bundle folder called `./build`
* Move the `./build` folder into `./simple-backend/stave_backend/lib/`
* Run `pip install -e ./`

You can refer to the workflow [here](https://github.com/asyml/stave/blob/4be7ccdead51324100dc4befbeb5aefa6565daf2/.github/workflows/pypi.yml#L33) to see what steps are required for packaging.

**Comment by Piyush13y** [comment]
@mylibrar Thanks for that.
Is it at all possible to run the current clinical_processing_pipeline.py with the present code? I followed README and I landed up on the query_chatbot.json showing up in the annotation viewer instead of the dialogue like interface. Like so
 
<img width="1309" alt="Screen Shot 2022-04-27 at 11 54 27 AM" src="https://user-images.githubusercontent.com/14886942/165599206-0d100b60-2a18-48b8-b968-a494dde12950.png">

**Comment by Piyush13y** [comment]
Nevermind, resolved this^

**Comment by Piyush13y** [comment]
> @mylibrar Thanks for that. Is it at all possible to run the **current** `clinical_processing_pipeline.py` i.e. with the present code? I followed README and I landed up on the query_chatbot.json showing up in the annotation viewer instead of the dialogue like interface. Like so
> 
> <img alt="Screen Shot 2022-04-27 at 11 54 27 AM" width="1309" src="https://user-images.githubusercontent.com/14886942/165599206-0d100b60-2a18-48b8-b968-a494dde12950.png">

Nevermind, resolved this

**Comment by Piyush13y** [comment]
I was trying out the following design to get the skeleton working and just thought I would share it with you. Please advise or suggest if you have anything in mind. The code is in works,

![9206E1C5-0E6D-4982-BF18-E29606236CCE](https://user-images.githubusercontent.com/14886942/166170124-a830ed25-060f-4044-a381-f6fb95283270.png)

**Comment by mylibrar** [comment]
The overall design looks good to me. One thing to note is that PL1 is already implemented by `stave`. Any `stave` project with its layout configured to `DialogueBox` should be able to load this [pipeline](https://github.com/asyml/stave/blob/4be7ccdead51324100dc4befbeb5aefa6565daf2/simple-backend/stave_backend/handlers/nlp.py#L49). So you only need to implement PL2 and make sure it's compatible with PL1. You can also use the `Eliza` project in `stave` to test your remote service (refer to this [tutorial](https://asyml-forte.readthedocs.io/en/latest/notebook_tutorial/tutorial_eliza.html) for details).

**Comment by Piyush13y** [comment]
@mylibrar I realized that all string attributes in the annotations are truncated after 3 characters. Is that configurable in stave?

**Comment by mylibrar** [comment]
> @mylibrar I realized that all string attributes in the annotations are truncated after 3 characters. Is that configurable in stave?

I guess it's not configurable now. Looks like it's hardcoded when displaying a string attribute in [floating](https://github.com/asyml/stave/blob/master/src/nlpviewer/lib/utils.ts#L48) and in [sidebar](https://github.com/asyml/stave/blob/master/src/nlpviewer/lib/utils.ts#L67).

**Comment by Piyush13y** [comment]
@mylibrar 
I am done with all the other changes, and was trying to refactor utterance_searcher.py with the latest APIs. However, I see that the API calls aren't going through from the utterance_searcher.py file. On the other hand, when I use the same APIs in the clinical_processing_pipeline.py file, they work just fine. When trying to call them from utterance_searcher.py, I can see in the browser, that the API call goes on indefinitely and the page just becomes unresponsive. This happens with any call that I try, be it login, create document, etc. 

<img width="565" alt="Screen Shot 2022-05-19 at 2 35 31 AM" src="https://user-images.githubusercontent.com/14886942/169266949-92f42ebb-fb44-4370-8a54-34c4571b934e.png">

The control flow gets stuck at Line 90, printing the print statement above but not below the login API. I am clueless as to what might be happening here.
